import { ref, computed } from 'vue'
import { sampleArticles } from '../data/sampleNews.js'

export function useNews() {
  const allData = ref({})        // date-grouped: { "2026-03-06": [...], ... }
  const availableDates = ref([]) // sorted descending
  const selectedDate = ref(null)
  const loading = ref(false)
  const error = ref(null)
  const selectedCategory = ref('all')

  async function fetchNews() {
    loading.value = true
    error.value = null

    // Try local /news.json (generated by sync-news.mjs from Obsidian daily notes)
    try {
      const res = await fetch('/news.json', { cache: 'no-store' })
      if (res.ok) {
        const data = await res.json()

        // New format: date-grouped object { "YYYY-MM-DD": [...] }
        if (data && typeof data === 'object' && !Array.isArray(data)) {
          allData.value = data
          availableDates.value = Object.keys(data).sort().reverse()
          if (availableDates.value.length > 0) {
            selectedDate.value = availableDates.value[0]
          }
          loading.value = false
          return
        }

        // Legacy flat array format
        if (Array.isArray(data) && data.length > 0) {
          const grouped = {}
          for (const article of data) {
            const date = article.publishedAt?.slice(0, 10) || 'unknown'
            if (!grouped[date]) grouped[date] = []
            grouped[date].push(article)
          }
          allData.value = grouped
          availableDates.value = Object.keys(grouped).sort().reverse()
          if (availableDates.value.length > 0) {
            selectedDate.value = availableDates.value[0]
          }
          loading.value = false
          return
        }
      }
    } catch {
      // /news.json not available — fall through to sample data
    }

    // Final fallback — hardcoded sample data (works offline / in dev)
    const grouped = {}
    for (const article of sampleArticles) {
      const date = article.publishedAt?.slice(0, 10) || 'unknown'
      if (!grouped[date]) grouped[date] = []
      grouped[date].push(article)
    }
    allData.value = grouped
    availableDates.value = Object.keys(grouped).sort().reverse()
    if (availableDates.value.length > 0) {
      selectedDate.value = availableDates.value[0]
    }
    loading.value = false
  }

  const articles = computed(() => {
    if (!selectedDate.value || !allData.value[selectedDate.value]) return []
    return allData.value[selectedDate.value]
  })

  const filteredArticles = computed(() => {
    if (selectedCategory.value === 'all') return articles.value
    return articles.value.filter(a => a.category === selectedCategory.value)
  })

  function getDateLabel(dateString) {
    const date = new Date(dateString)
    const now = new Date()
    const diffMs = now - date
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
    if (diffDays === 0) return 'Today'
    if (diffDays === 1) return 'Yesterday'
    if (diffDays === 2) return '2 Days Ago'
    if (diffDays === 3) return '3 Days Ago'
    return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })
  }

  // For the date switcher: format as "MM-DD" and mark today
  function formatDateLabel(dateStr) {
    const today = new Date().toISOString().slice(0, 10)
    if (dateStr === today) return { label: dateStr.slice(5), isToday: true }
    return { label: dateStr.slice(5), isToday: false }
  }

  const groupedArticles = computed(() => {
    return [{
      label: selectedDate.value ? getDateLabel(selectedDate.value + 'T00:00:00') : '',
      articles: filteredArticles.value,
    }].filter(g => g.articles.length > 0)
  })

  return {
    articles,
    loading,
    error,
    selectedCategory,
    selectedDate,
    availableDates,
    filteredArticles,
    groupedArticles,
    fetchNews,
    getDateLabel,
    formatDateLabel,
  }
}
