import { ref, computed } from 'vue'
import { sampleArticles } from '../data/sampleNews.js'

export function useNews() {
  const articles = ref([])
  const loading = ref(false)
  const error = ref(null)
  const selectedCategory = ref('all')

  const apiKey = import.meta.env.VITE_NEWS_API_KEY

  async function fetchNews() {
    loading.value = true
    error.value = null

    // 1. Try local /news.json (generated by sync-news.mjs from Obsidian daily notes)
    try {
      const res = await fetch('/news.json', { cache: 'no-store' })
      if (res.ok) {
        const data = await res.json()
        if (Array.isArray(data) && data.length > 0) {
          articles.value = data
          loading.value = false
          return
        }
      }
    } catch {
      // /news.json not available — fall through to other sources
    }

    // 2. Try NewsAPI (requires VITE_NEWS_API_KEY)
    if (apiKey) {
      try {
        const category = selectedCategory.value === 'all' ? 'general' : selectedCategory.value
        const response = await fetch(
          `https://newsapi.org/v2/top-headlines?category=${category}&language=en&pageSize=40&apiKey=${apiKey}`
        )
        if (!response.ok) throw new Error('API request failed')
        const data = await response.json()
        articles.value = data.articles
          .filter(a => a.title && a.title !== '[Removed]')
          .map((a, i) => ({ ...a, id: i, category: category }))
        loading.value = false
        return
      } catch (err) {
        console.warn('NewsAPI failed, falling back to sample data:', err.message)
      }
    }

    // 3. Final fallback — hardcoded sample data (works offline / in dev)
    articles.value = sampleArticles
    loading.value = false
  }

  const filteredArticles = computed(() => {
    if (selectedCategory.value === 'all') return articles.value
    return articles.value.filter(a => a.category === selectedCategory.value)
  })

  function getDateLabel(dateString) {
    const date = new Date(dateString)
    const now = new Date()
    const diffMs = now - date
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
    if (diffDays === 0) return 'Today'
    if (diffDays === 1) return 'Yesterday'
    if (diffDays === 2) return '2 Days Ago'
    if (diffDays === 3) return '3 Days Ago'
    return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })
  }

  const groupedArticles = computed(() => {
    const groups = {}
    const order = []

    for (const article of filteredArticles.value) {
      const label = getDateLabel(article.publishedAt)
      if (!groups[label]) {
        groups[label] = []
        order.push(label)
      }
      groups[label].push(article)
    }

    return order.map(label => ({ label, articles: groups[label] }))
  })

  return {
    articles,
    loading,
    error,
    selectedCategory,
    filteredArticles,
    groupedArticles,
    fetchNews,
    getDateLabel,
  }
}
